repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.12
    hooks:
      - id: ruff
        args: [--fix]
        stages: [pre-commit]
      - id: ruff-format
        stages: [pre-commit]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
        stages: [pre-commit]
      - id: trailing-whitespace
        stages: [pre-commit]
      - id: check-json
        name: Check JSON syntax (package.json, etc.)
        stages: [pre-commit]
      - id: check-yaml
        name: Check YAML syntax
        stages: [pre-commit]
      - id: check-merge-conflict
        stages: [pre-commit]
  - repo: local
    hooks:
      - id: pytest
        name: pytest (backend)
        entry: bash -lc 'cd backend && uv run pytest'
        language: system
        pass_filenames: false
        stages: [pre-push]
      - id: forbid-naive-datetime
        name: Forbid naive datetime usage
        entry: bash
        args:
          - -c
          - |
            # Check for naive datetime usage in backend code (excluding comments, docstrings, and binary files)
            if grep -r --line-number --exclude-dir="__pycache__" "datetime\.utcnow(" backend/app/ | grep -v "Replacement for datetime.utcnow" | grep -v "#.*datetime\.utcnow"; then
              echo "ERROR: Found datetime.utcnow() usage. Use app.utils.time.utc_now() instead."
              exit 1
            fi
            if grep -r --line-number --exclude-dir="__pycache__" "datetime\.now()" backend/app/ | grep -v "timezone.utc" | grep -v "tz=timezone.utc" | grep -v "#.*datetime\.now"; then
              echo "ERROR: Found naive datetime.now() usage. Use app.utils.time.utc_now() instead."
              exit 1
            fi
            echo "✓ No naive datetime usage found"
        language: system
        files: ^backend/app/.*\.py$
        stages: [pre-commit]
