repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.12
    hooks:
      - id: ruff
        args: [--fix]
        stages: [pre-commit]
      - id: ruff-format
        stages: [pre-commit]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
        stages: [pre-commit]
      - id: trailing-whitespace
        stages: [pre-commit]
      - id: check-json
        name: Check JSON syntax (package.json, etc.)
        stages: [pre-commit]
      - id: check-yaml
        name: Check YAML syntax
        stages: [pre-commit]
      - id: check-merge-conflict
        stages: [pre-commit]
  - repo: local
    hooks:
      - id: pytest
        name: pytest (backend)
        entry: bash -lc 'cd backend && uv run pytest'
        language: system
        pass_filenames: false
        stages: [pre-push]
