services:
  api:
    build: ./backend
    env_file: ./backend/.env
    ports: ["8080:8080"]
    command: uv run uvicorn app.main:app --host 0.0.0.0 --port 8080
  web:
    build: ./frontend
    env_file: ./frontend/.env.local
    ports: ["3000:3000"]
    command: npm run dev
