name: CI/CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      ref:
        description: "Git ref to deploy (branch, tag, or SHA)"
        required: false
        default: "main"
      build_image:
        description: "Build & push image before deploy?"
        required: false
        type: boolean
        default: true

jobs:
  backend-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Quick CI sanity check
        run: echo "CI ran on $GITHUB_SHA"

  coverage-badge:
    runs-on: ubuntu-latest
    needs: backend-ci
    permissions:
      contents: write   # needed to commit docs/coverage.svg
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install uv + tools
        run: |
          python -m pip install --upgrade pip uv
          uv pip install pytest pytest-cov genbadge[coverage]
      - name: Sync backend deps
        working-directory: backend
        run: |
          uv venv --python 3.12
          uv sync
      - name: Run tests with coverage (from backend/)
        working-directory: backend
        run: |
          # adjust --cov target if your package name differs
          uv run pytest -q --cov=app --cov-report=xml
          test -f coverage.xml
      - name: Generate SVG badge at repo root
        working-directory: backend
        run: |
          mkdir -p ../docs
          uv run genbadge coverage -i coverage.xml -o ../docs/coverage.svg
          ls -l ../docs/coverage.svg
      - name: Upload coverage artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage-artifacts
          path: |
            backend/coverage.xml
            docs/coverage.svg
      - name: Commit badge to main (only on main)
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          if git diff --quiet docs/coverage.svg; then
            echo "No badge change."
          else
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add docs/coverage.svg
            git commit -m "chore(ci): update coverage badge [skip ci]"
            git push
          fi

  backend-deploy:
    needs: backend-ci
    runs-on: ubuntu-latest
    if: >
      ${{
        (github.event_name == 'push' && github.ref == 'refs/heads/main')
        || github.event_name == 'workflow_dispatch'
      }}
    defaults:
      run:
        working-directory: backend
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref || 'main' }}
      - name: Google Cloud auth
        uses: google-github-actio
