# Add under `jobs:` in .github/workflows/ci-cd.yml

  coverage-badge:
    runs-on: ubuntu-latest
    # optional: wait for your lightweight CI job first
    needs: backend-ci
    permissions:
      contents: write   # needed to push docs/coverage.svg to the repo
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install test + badge tooling
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov genbadge[coverage]

      - name: Run tests with coverage (from backend/)
        working-directory: backend
        run: |
          # Adjust --cov target if your package name differs
          pytest -q --cov=app --cov-report=xml
          test -f coverage.xml

      - name: Generate SVG badge at repo root
        working-directory: backend
        run: |
          mkdir -p ../docs
          genbadge coverage -i coverage.xml -o ../docs/coverage.svg
          ls -l ../docs/coverage.svg

      - name: Upload coverage artifacts (for debugging)
        uses: actions/upload-artifact@v4
        with:
          name: coverage-artifacts
          path: |
            backend/coverage.xml
            docs/coverage.svg

      - name: Commit badge to main (only on main)
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          if git diff --quiet docs/coverage.svg; then
            echo "No badge change."
          else
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add docs/coverage.svg
            git commit -m "chore(ci): update coverage badge [skip ci]"
            git push
          fi
